export const ADD_WINE = "ADD_WINE"
export const DELETE_WINE = "DELETE_WINE"
export const SELECT_WINE = "SELECT_WINE"
export const DESELECT_WINE = "DESELECT_WINE"
export const UI_START_LOADING = "UI_START_LOADING"
export const UI_STOP_LOADING = "UI_STOP_LOADING"
export const AUTH_SET_TOKEN = "AUTH_SET_TOKEN"
export const NEW_VINTAGE = "NEW_VINTAGE"
export const NEW_WINE_NAME = "NEW_WINE_NAME"
export const NEW_WINE_MAKER = "NEW_WINE_MAKER"
export const NEW_WINE_VARIETAL = "NEW_WINE_VARIETAL"
export const NEW_WINE_GRAPES = "NEW_WINE_GRAPES"
export const NEW_WINE_NOTES = "NEW_WINE_NOTES"



 

